services:
- type: web
  runtime: node
  name: nodejs-blueprint-render
  # env: node
  repo: https://github.com/eduardevs/serverless_cloud_blueprint_render.git
  buildCommand: npm install
  startCommand: npm run start
  plan: free
  autoDeploy: true
  envVars:
  - key: DATABASE_URL
    sync: false
    
databases:
  - name: database
    plan: free
    region: frankfurt
    ipAllowList: [] # only allow internal connections
    postgresMajorVersion: 15
# databases:
#     - name: testdb
#       type: database
#       region: frankfurt
#       env:
#         - name: DB_USER
#           value: admin
#         - name: DB_PASS
#           value: admin
#         - name: DB_NAME
#           value: admin
